services:
  postgres:
    image: postgres:16
    container_name: guss_pg
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guss
    ports:
      - "5433:5432"     # ← ИСПРАВЛЕНО (больше не конфликтует с assistchat)
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - guss_net

  backend:
    build: ./backend
    container_name: guss_backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@guss_pg:5432/guss
      NODE_ENV: production
    volumes:
      - ./backend:/app
    command: [ "/app/wait-for-postgres.sh", "guss_pg", "5432", "sh", "-c", "npm run build && npm run migrate && npm run start" ]
    ports:
      - "3010:3000"
    networks:
      - guss_net

  frontend:
    build: ./frontend
    container_name: guss_frontend
    ports:
      - "5173:4173"
    networks:
      - guss_net

volumes:
  pgdata:

networks:
  guss_net:
